### ISSUE TITLE
Add some cool CSS to the UI

### ISSUE THREAD

**Issue by Presto412** [Presto412/StoreV#4]
Currently, the UI is pure HTML and solves functionality. You can add some CSS to make it look good!
Here's how it currently looks:
![image](https://user-images.githubusercontent.com/26374855/95000400-00d88300-05de-11eb-9249-fe4403f865f0.png)
![image](https://user-images.githubusercontent.com/26374855/95000403-0c2bae80-05de-11eb-927f-5b91fa0d74fb.png)

Any improvements appreciated!

**Comment by marcodeanda** [comment]
Hi! I'd like to try helping out, could you assign me a task?

**Comment by Presto412** [comment]
Sure @marcodeanda , thanks!
